server:
  port: 10001
  servlet:
    context-path: /isrpAuth
spring:
  application:
    name: isrp-auth
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: localhost
    port: 6379
feign:
  httpclient:
    enabled: true  # 支持httpclient的开关
    max-connections: 200
    max-connections-per-route: 50
jwt:
  tokenHeader: Authorization
  secret: 12BC9bd67b237ad3f9c7ce7286b858ae5b7ae418e2baedf3e46ff244b98f861b
  expiration: 604800
  tokenHead: Bearer

