server:
  port: 9527
spring:
  application:
    name: isrp-gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: order_router
          uri: lb://isrp-order
          predicates:
            - Path=/isrpOrder/**

        - id: user_router
          uri: lb://isrp-user
          predicates:
            - Path=/isrpUser/**

        - id: goods_router
          uri: lb://isrp-goods
          predicates:
            - Path=/isrpGoods/**
        - id: gateway_404
          uri: lb://isrp-gateway
          predicates:
            - Path=/**
          filters:
            - RedirectTo=302, http://localhost:9527/
  main:
    web-application-type: reactive

