server:
  port: 9527
spring:
  application:
    name: isrp-gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowedOrigins: "*" # 允许哪些网站的跨域请求
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
      routes:
        - id: order_router
          uri: lb://isrp-order
          predicates:
            - Path=/isrpOrder/**

        - id: user_router
          uri: lb://isrp-user
          predicates:
            - Path=/isrpUser/**

        - id: goods_router
          uri: lb://isrp-goods
          predicates:
            - Path=/isrpGoods/**

        - id: auth_router
          uri: lb://isrp-auth
          predicates:
            - Path=/isrpAuth/**

        - id: gateway_404
          uri: lb://isrp-gateway
          predicates:
            - Path=/**
          filters:
            - RedirectTo=302, http://localhost:9527/
  main:
    web-application-type: reactive

