server:
  port: 9527
spring:
  application:
    name: isrp_gateway
  cloud:
    gateway:
      routes:
        - id: order_router
          uri: http://localhost:20000
          predicates:
            - Path=/isrpOrder/**

        - id: user_router
          uri: http://localhost:10000
          predicates:
            - Path=/isrpUser/**

        - id: goods_router
          uri: http://localhost:30000
          predicates:
            - Path=/isrpGoods/**
  main:
    web-application-type: reactive

