spring:
  application:
    name: isrp-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 9568
  servlet:
    context-path: /naco
management:
  endpoint:
    web:
      exposure:
        include: '*'
