spring:
  application:
    name: isrp-order
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: static/**
  main:
    allow-circular-references: true
  devtools:
    livereload:
      port: 20001
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1xb8e55nhvgonc4so.mysql.rds.aliyuncs.com/isrp_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: isrp_mysql
    password: ISRPisrp@20220613#
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: localhost
    port: 6379
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 20000
  servlet:
    context-path: /isrpOrder
feign:
  httpclient:
    enabled: true  # 支持httpclient的开关
    max-connections: 200
    max-connections-per-route: 50
jwt:
  tokenHeader: Authorization
  secret: 12BC9bd67b237ad3f9c7ce7286b858ae5b7ae418e2baedf3e46ff244b98f861b
  expiration: 604800
  tokenHead: Bearer
