spring:
  application:
    name: isrp_order
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: static/**

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1xb8e55nhvgonc4so.mysql.rds.aliyuncs.com/isrp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: isrp_mysql
    password: ISRPisrp@20220613#
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  jpa:
    open-in-view: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 20000
  servlet:
    context-path: /isrpOrder
