spring:
  web:
    resources:
      static-locations: classpath:/static/
  application:
    name: isrp-user
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: static/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1xb8e55nhvgonc4so.mysql.rds.aliyuncs.com/isrp_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: isrp_mysql
    password: ISRPisrp@20220613#
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  jpa:
    open-in-view: false
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: localhost
    port: 6379
  devtools:
    livereload:
      port: 10002
  thymeleaf:
    cache: false
    prefix: classpath:/templates
    mode: HTML
    enabled: true
    encoding: utf-8
    suffix: .html
  mail:
    host: smtp.qq.com
    port: 465
    username: 532985761@qq.com
    password: mbiytteaqvizcbah
    protocol: smtps
    properties:
      from: 532985761@qq.com
      mail:
        smtp:
          ssl:
            enable: true
feign:
  httpclient:
    enabled: true # 支持httpclient的开关
    max-connections: 200
    max-connections-per-route: 50
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 10000
  servlet:
    context-path: /isrpUser
jwt:
  tokenHeader: Authorization
  secret: 12BC9bd67b237ad3f9c7ce7286b858ae5b7ae418e2baedf3e46ff244b98f861b
  expiration: 604800
  tokenHead: Bearer
